apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  namespace: default
data:
  ALLOW_ANONYMOUS_LOGIN: "yes" 
  ZOO_LOG_LEVEL:  "DEBUG"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: default
data:
  KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper-svc:2181"
  KAFKA_BROKER_ID: "1"
  KAFKA_LISTENERS: "PLAINTEXT://:9092,EXTERNAL://:9094"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092,EXTERNAL://54.160.93.109:30021"
  ALLOW_PLAINTEXT_LISTENER: "yes"
  broker.id: "1"
  ALLOW_PLAINTEXT_LISTENER: "yes"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:PLAINTEXT, PLAINTEXT:PLAINTEXT"