apiVersion: v1 
kind: Service 
metadata:  
   name: kafka-svc
   labels:
     app: kafka
spec:
   ports:  
   - name: internal-access
     protocol: TCP
     port: 9092 
     targetPort: 9092
   - name: external-access
     protocol: TCP
     port: 9094 
     targetPort: 9094
     nodePort: 30021
   selector:  
     app: kafka
   type: NodePort