apiVersion: v1
kind: Service
metadata:
  name: test-zookeeper-svc
  labels:
    app: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
spec:
  ports:
    - protocol: TCP
      port: 2181
      nodePort: 30020
  type: NodePort
  selector:
    app: zookeeper