apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:3.6.1
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER
          value: zookeeper
        
          