apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-configs
  namespace: default
data:
  KAFKA_CFG_ZOOKEEPER_CONNECT: "zk-s:2181"
  KAFKA_BROKER_ID: "1"
  KAFKA_LISTENERS: "PLAINTEXT://:9092,EXTERNAL://:9094"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092,EXTERNAL://54.160.93.109:30021"
  ALLOW_PLAINTEXT_LISTENER: "yes"
  broker.id: "1"
  ALLOW_PLAINTEXT_LISTENER: "yes"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:PLAINTEXT, PLAINTEXT:PLAINTEXT"
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: kafkabroker
   labels:
     app: kafkaApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkaApp
  template:
    metadata:
      labels:
        app: kafkaApp 
    spec:  
      containers:  
      - name: kafka-broker
        image: bitnami/kafka
        ports:  
        - containerPort: 9092
        envFrom:
        - configMapRef:
            name: kafka-configs